openapi: 3.0.3
info:
  title: Shelly - IoT devices
  description: Shelly
  version: 1.0.0

tags:
  - name: Shelly
    description: IoT

paths: { }

components:
  schemas:
    ShellyUniStatusResponse:
      type: object
      properties:
        time:
          type: string
          format: time
        unixtime:
          type: integer
        wifi_sta:
          $ref: '#/components/schemas/WifiStatus'
        cloud:
          $ref: '#/components/schemas/Cloud'
        relays:
          type: array
          items:
            $ref: '#/components/schemas/Relay'
        ext_temperature:
          $ref: '#/components/schemas/ExternalTemperature'
    WifiStatus:
      type: object
      properties:
        connected:
          type: boolean
        ssid:
          type: string
        ip:
          type: string
        rssi:
          type: integer
    Cloud:
      type: object
      properties:
        enabled:
          type: boolean
        connected:
          type: boolean
    Relay:
      type: object
      properties:
        ison:
          type: boolean
        has_timer:
          type: boolean
        timer_started:
          type: integer
        timer_duration:
          type: integer
        timer_remaining:
          type: integer
        source:
          type: string
    ExternalTemperature:
      type: object
      additionalProperties:
        type: object
        properties:
          hwID:
            type: string
          tC:
            type: number
            format: float