/*
 * Shelly - IoT devices
 * Shelly
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.cholewa.shelly.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import jakarta.validation.constraints.*;

/**
 * Gets or Sets PayloadType
 */
public enum PayloadType {

    TX("00"),

    CONFIG("01"),

    TX_EXT("02"),

    RX("03"),

    STATUS("06"),

    ERROR("10");

    private String value;

    PayloadType(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static PayloadType fromValue(String value) {
        for (PayloadType b : PayloadType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}
